micronaut:
  application:
    name: todoapp

#hibernate:
#  hbm2ddl:
#    auto: update
#    show_sql: true
    #  cache:
    #    queries: false
    #    use_second_level_cache: true
    #    use_query_cache: false
    # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
  #  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  url: jdbc:mysql://localhost:3306/todoapp?serverTimezone=EST5EDT
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: ''
  show_sql: true

hibernate:
  hbm2ddl:
    auto: update
  show_sql: true