micronaut:
  application:
    name: todoapp
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne

dataSource:
  pooled: true
  jmxExport: true
  url: jdbc:mysql://localhost:3306/todoapp?serverTimezone=EST5EDT
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: ''
  show_sql: true

hibernate:
  # enable_lazy_load_no_trans: false
  hbm2ddl:
    auto: update
  show_sql: true
#  cache:
#    queries: true
#    use_second_level_cache: true
#    use_query_cache: true
#    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

